version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/blogger_app

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
    - location: scripts/app_dependecy_and_migrations.sh
      timeout: 500
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
