version: 0.2
phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python manage.py test
  build:
    commands:
      - zip -r django-app.zip .
  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - django-app.zip
  discard-paths: yes
