version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt  # Install Python dependencies

  pre_build:
    commands:
      - echo "Running pre-build scripts..."
      - python manage.py check  # Run Django system checks

  build:
    commands:
      - echo "Running build scripts..."
      - python manage.py collectstatic --noinput  # Collect static files for production
      - python manage.py migrate  # Apply database migrations

  post_build:
    commands:
      - echo "Running post-build scripts..."

artifacts:
  files:
    - "**/*"  # Include all necessary files for deployment
  discard-paths: yes

cache:
  paths:
    - "/root/.cache/pip"  # Cache pip dependencies for faster builds
